dotfiles_dir = "dotfiles"

[settings]
vars = [ "vars.toml" ]
prehooks = ["./install.sh"]

[settings.dots]
alacritty = { source = "alacritty", target = ".config/alacritty" }

# Git
gitconfig = { source = "git/gitconfig", target = ".gitconfig" }
gitconfig-kaizen = { source = "git/gitconfig-kaizen", target = ".gitconfig-kaizen" }
gitattributes = { source = "git/gitattributes", target = ".gitattributes" }
gitignore = { source = "git/gitignore", target = ".gitignore" }

# Zsh
zsh = { source = "zsh/zshrc", target = ".zshrc" }
zsh_env = { source = "zsh/zshenv", target = ".zshenv" }
zsh_aliases = { source = "zsh/aliases", target = ".aliases" }
zsh_exports = { source = "zsh/exports", target = ".exports" }
zsh_functions = { source = "zsh/functions", target = ".functions" }
zsh_path = { source = "zsh/path", target = ".path" }

# Sharship
starship = { source = "starship/starship.toml", target = ".config/starship.toml" }

# Dir Colors (Nord theme)
dir_colors = { source = "dir_colors/dir_colors", target = ".dir_colors" }

# Tmux
tmux = { source = "tmux/tmux.conf", target = ".tmux.conf" }

# Vim
vim = { source = "vim/vimrc", target = ".vimrc" }
nvim = { source = "nvim", target = ".config/nvim" }