[directory]
truncation_length = 0
truncate_to_repo = false

[hostname]
ssh_only = false
format =  "on [$hostname](bold red) "
disabled = false

[username]
style_user = "white bold"
style_root = "black bold"
format = "[$user]($style) "
disabled = false
show_always = true
