# Load the shell dotfiles, and then some:
# * ~/.path can be used to extend `$PATH`.
for file in ~/.{path,exports,aliases,functions}; do
	[ -r "$file" ] && source "$file"
done
unset file

# Platform testing
platform='unknown'
unamestr=`uname`
if [[ "$unamestr" == 'Linux' ]]; then
	platform='linux'
elif [[ "$unamestr" == 'Darwin' ]]; then
	platform='macos'
fi

# rbenv
# Use rbenv to pick a Ruby version for your application and guarantee that
# your development environment matches production.
# https://github.com/rbenv/rbenv
if [ -d ~/.rbenv/bin ] ; then
	export PATH="$HOME/.rbenv/bin":$PATH
	eval "$(rbenv init -)"
fi

# dircolors
if [ -f ~/.dir_colors ] ; then
	eval `dircolors ~/.dir_colors`
fi

export TERM=xterm-256color

# Starship
# The minimal, blazing-fast, and infinitely customizable prompt for any shell!
# https://starship.rs/
eval "$(starship init zsh)"

# Volta
# The Hassle-Free JavaScript Tool Manager
# https://volta.sh/
export VOLTA_HOME="$HOME/.volta"
export PATH="$VOLTA_HOME/bin:$PATH"

# Completion
fpath=(~/dotfiles/zsh/completions $fpath)
autoload -Uz compinit
compinit

# ctrl+w: delete a word
custom-backward-delete-word() {
    local WORDCHARS=${WORDCHARS/\//}
    zle backward-delete-word
}
zle -N custom-backward-delete-word
bindkey '^W' custom-backward-delete-word
